version: '3'

networks:
  nw_wapp_simple_todo_list:

services:
  nginx:
    restart: always
    container_name: wapp_simple_todo_list_nginx
    hostname: wapp_simple_todo_list.local
    build:
      context: ./nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${WORK_PATH}:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - php_fpm
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - nw_wapp_simple_todo_list

  php_fpm:
    restart: always
    container_name: wapp_simple_todo_list_php_fpm
    hostname: php_fpm
    build:
      context: ./php-workspace
      dockerfile: ./Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    volumes:
      - ${WORK_PATH}:/var/www
      - ./php-workspace/logs/log1:/var/log/
      - ./php-workspace/logs/log2:/usr/local/var/log
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    env_file:
      - ./.env
    networks:
      - nw_wapp_simple_todo_list